# Generated by Django 5.1.6 on 2025-09-29 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_classification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classification',
        ),
    ]
